const rawData = [
  // ── Aatrox ──
  {champion:"Aatrox",r1:"The Darkin Blade",r2:"Starforged Gauntlets",r3:"The Beast Within",star:"6*-34",player:"Nazoric, TwoStickmen"},
  {champion:"Aatrox",r1:"The Darkin Blade",r2:"Starforged Gauntlets",r3:"Echoing Spirit",star:"6*-50",player:"Bushi"},
  {champion:"Aatrox",r1:"The Darkin Blade",r2:"Starforged Gauntlets",r3:"Crownguard Inheritance",star:"6*-50",player:"LehmonNation"},
  {champion:"Aatrox",r1:"Starforged Gauntlets",r2:"Luminous Orb",r3:"The Beast Within",star:"6*-49",player:"RoloRolla, The Moral Support"},
  {champion:"Aatrox",r1:"Disciple of Shadows",r2:"Succubus's Brand",r3:"The Beast Within",star:"6*-37",player:"Hooded, PetiB"},
  {champion:"Aatrox",r1:"Disciple of Shadows",r2:"Succubus's Brand",r3:"Spirit Forge",star:"6*-37",player:"HPDARK"},
  // ── Ahri ──
  {champion:"Ahri",r1:"Hidden Tome",r2:"Found Fortune",r3:"Hymn of Valor",star:"4*-35",player:"BumpyRoad, Mike Hamster"},
  {champion:"Ahri",r1:"Echoing Spirit",r2:"Hidden Tome",r3:"The Curator's Gatebreaker",star:"4*-38",player:"aoeuid"},
  {champion:"Ahri",r1:"Echoing Spirit",r2:"Hidden Tome",r3:"Hymn of Valor",star:"5*-39",player:"2ndTony, u/Least-Coconut-3004, baseball7000"},
  {champion:"Ahri",r1:"Echoing Spirit",r2:"Hidden Tome",r3:"The Scourge's Stash",star:"4*-35",player:"BlackPolarBear"},
  {champion:"Ahri",r1:"Echoing Spirit",r2:"Packed Powder",r3:"Found Fortune",star:"6*-45",player:"HPDARK, Tangolino, Bushi"},
  {champion:"Ahri",r1:"Echoing Spirit",r2:"Packed Powder",r3:"Guardian's Orb",star:"6*-37",player:"TwoStickmen"},
  {champion:"Ahri",r1:"Echoing Spirit",r2:"Searing Brilliance",r3:"Guardian's Orb",star:"6*-50",player:"cyclonus101"},
  {champion:"Ahri",r1:"Echoing Spirit",r2:"Found Fortune",r3:"Guardian's Orb",star:"4*-38",player:"u/MinhTrocs"},
  {champion:"Ahri",r1:"Echoing Spirit",r2:"Hymn of Valor",r3:"Lost Chapter",star:"6*-36",player:"Yuemoonn"},
  {champion:"Ahri",r1:"Wicked Harvest",r2:"The Curator's Gatebreaker",r3:"Voidborne Carapace",star:"3*-36",player:"Aizen"},
  {champion:"Ahri",r1:"Packed Powder",r2:"Found Fortune",r3:"Searing Brilliance",star:"6*-41",player:"Nazoric"},
  {champion:"Ahri",r1:"Packed Powder",r2:"Hidden Tome",r3:"Hymn of Valor",star:"6*-50",player:"u/Airtnp"},
  // ── Akshan ──
  {champion:"Akshan",r1:"Echoing Spirit",r2:"Perfect Hex Core",r3:"Voidborne Carapace",star:"4*-38",player:"msh"},
  {champion:"Akshan",r1:"Echoing Spirit",r2:"Searing Brilliance",r3:"Voidborne Carapace",star:"4*-37",player:"aoeuid"},
  {champion:"Akshan",r1:"Echoing Spirit",r2:"Scoundrel Hunter",r3:"Chemtech Duplicator",star:"6*-38",player:"Tangolino, Bushi, ProfSE"},
  {champion:"Akshan",r1:"Echoing Spirit",r2:"Chosen by the Stars",r3:"Chemtech Duplicator",star:"6*-50",player:"Hooded, jewl, lolguy999"},
  {champion:"Akshan",r1:"Echoing Spirit",r2:"Chosen by the Stars",r3:"Hidden Tome",star:"6*-50",player:"cyclonus101"},
  {champion:"Akshan",r1:"Echoing Spirit",r2:"Hidden Tome",r3:"Found Fortune",star:"4*-35",player:"VodopadUmraza"},
  {champion:"Akshan",r1:"Chosen by the Stars",r2:"Frozen Tomb",r3:"Perfect Hex Core",star:"6*-38",player:"Nazoric"},
  {champion:"Akshan",r1:"Chosen by the Stars",r2:"Searing Brilliance",r3:"Perfect Hex Core",star:"6*-37",player:"TwoStickmen"},
  {champion:"Akshan",r1:"Chosen by the Stars",r2:"Loaded Dice",r3:"Found Fortune",star:"6*-39",player:"HPDARK"},
  // ── Ambessa ──
  {champion:"Ambessa",r1:"Perfect Hex Core",r2:"Searing Brilliance",r3:"Hidden Tome",star:"4*-40",player:"aoeuid"},
  {champion:"Ambessa",r1:"Starforged Gauntlets",r2:"Champion's Purse",r3:"Death's Foil",star:"5*-40",player:"Nazoric"},
  {champion:"Ambessa",r1:"Swain's Raven Army",r2:"Packed Powder",r3:"Found Fortune",star:"6*-36",player:"Catamarano, RoloRolla, Sliverz"},
  {champion:"Ambessa",r1:"Starforged Gauntlets",r2:"Champion's Purse",r3:"Spectral Scissors",star:"6*-44",player:"Chengsta, ProfSE"},
  {champion:"Ambessa",r1:"Starforged Gauntlets",r2:"The Beast Within",r3:"Found Fortune",star:"6*-50",player:"Hooded"},
  {champion:"Ambessa",r1:"Perfect Hex Core",r2:"Black Shield",r3:"Found Fortune",star:"6*-50",player:"Magnum Flare"},
  {champion:"Ambessa",r1:"Living Weapon",r2:"Condenser",r3:"Stalker's Blade",star:"6*-33",player:"The Moral Support"},
  {champion:"Ambessa",r1:"Guardian Angel",r2:"Stalker's Blade",r3:"Stalker's Blade",star:"5*-41",player:"diaversai"},
  // ── Anivia ──
  {champion:"Anivia",r1:"Guardian Angel",r2:"Guardian Angel",r3:"Chemtech Duplicator",star:"4*-39",player:"HPDARK, TwoStickmen, Chengsta"},
  {champion:"Anivia",r1:"Starforged Gauntlets",r2:"Luminous Orb",r3:"Chemtech Duplicator",star:"6*-37",player:"Nazoric"},
  {champion:"Anivia",r1:"Guardian's Orb",r2:"Guardian Angel",r3:"Chemtech Duplicator",star:"6*-48",player:"SweeKayz"},
  {champion:"Anivia",r1:"Voidborne Carapace",r2:"Guardian Angel",r3:"Chemtech Duplicator",star:"6*-50",player:"aoeuid, Bushi, K0zt"},
  {champion:"Anivia",r1:"The Beast Within",r2:"Icon of Valhir",r3:"Chemtech Duplicator",star:"6*-36",player:"Nuimee"},
  // ── Annie ──
  {champion:"Annie",r1:"Dreadway Chase Gun",r2:"Guardian Angel",r3:"Ravenous Hydra",star:"3*-33",player:"Huffy"},
  {champion:"Annie",r1:"Dreadway Chase Gun",r2:"Guardian Angel",r3:"Z-Drive Prototype",star:"5*",player:"u/Odd_Dragonfruit_2100"},
  {champion:"Annie",r1:"Echoing Spirit",r2:"Twin Drakehounds",r3:"Galeforce",star:"6*-35",player:"Nazoric"},
  {champion:"Annie",r1:"Big Guns",r2:"Essence Theft",r3:"Whisper",star:"6*-48",player:"LehmonNation"},
  {champion:"Annie",r1:"Echoing Spirit",r2:"Deck of Destiny",r3:"Searing Brilliance",star:"6*-50",player:"Bushi, ProfSE"},
  // ── Ashe ──
  {champion:"Ashe",r1:"The Curator's Gatebreaker",r2:"The Curator's Gatebreaker",r3:"The Curator's Gatebreaker",star:"6*-37",player:"HPDARK, yuemoonn, Bushi"},
  {champion:"Ashe",r1:"Echoing Spirit",r2:"The Curator's Gatebreaker",r3:"The Curator's Gatebreaker",star:"6*-37",player:"Nazoric"},
  {champion:"Ashe",r1:"The Beast Within",r2:"Cease and Desist",r3:"Galeforce",star:"6*-50",player:"Sydiem"},
  {champion:"Ashe",r1:"The Beast Within",r2:"The Curator's Gatebreaker",r3:"The Curator's Gatebreaker",star:"6*-50",player:"diaversai, Katawazaki"},
  // ── Aurelion Sol ──
  {champion:"Aurelion Sol",r1:"Siren's Call",r2:"The Deceiver's Crest",r3:"Z-Drive Prototype",star:"2*",player:"u/Odd_Dragonfruit_2100"},
  {champion:"Aurelion Sol",r1:"Loaded Dice",r2:"The Deceiver's Crest",r3:"Stalker's Blade",star:"3*-33",player:"darkk100"},
  {champion:"Aurelion Sol",r1:"The Deceiver's Crest",r2:"Tempest Blade",r3:"Crownguard Inheritance",star:"3*-40",player:"diaversai"},
  {champion:"Aurelion Sol",r1:"Perfect Hex Core",r2:"The Grand General's Counterplan",r3:"Crownguard Inheritance",star:"3*-50",player:"u/Airtnp"},
  {champion:"Aurelion Sol",r1:"Perfect Hex Core",r2:"Starforged Gauntlets",r3:"Crownguard Inheritance",star:"4*-34",player:"2ndTony"},
  {champion:"Aurelion Sol",r1:"Perfect Hex Core",r2:"Starforged Gauntlets",r3:"Searing Brilliance",star:"3*-38",player:"Hooded"},
  {champion:"Aurelion Sol",r1:"Perfect Hex Core",r2:"Starforged Gauntlets",r3:"Siren's Call",star:"4*-37",player:"Alkaloid"},
  {champion:"Aurelion Sol",r1:"Perfect Hex Core",r2:"Starforged Gauntlets",r3:"Oath of the Guardians",star:"4*-45",player:"Erian"},
  {champion:"Aurelion Sol",r1:"Perfect Hex Core",r2:"Starforged Gauntlets",r3:"Portal Pals",star:"4*-50",player:"The Doomba"},
  {champion:"Aurelion Sol",r1:"Perfect Hex Core",r2:"Starforged Gauntlets",r3:"Protectors of Demacia",star:"4*-50",player:"Tangolino"},
  {champion:"Aurelion Sol",r1:"Perfect Hex Core",r2:"Starforged Gauntlets",r3:"Spellweaver's Symphony",star:"4*-38",player:"yuemoonn, ProfSE, Nazoric"},
  {champion:"Aurelion Sol",r1:"Echoing Spirit",r2:"Starforged Gauntlets",r3:"Spellweaver's Symphony",star:"4*-37",player:"HPDARK"},
  {champion:"Aurelion Sol",r1:"Perfect Hex Core",r2:"The Beast Within",r3:"Spellweaver's Symphony",star:"4*-38",player:"u/Simonirico"},
  {champion:"Aurelion Sol",r1:"Perfect Hex Core",r2:"Disciple of Shadows",r3:"Spellweaver's Symphony",star:"4*-50",player:"u/legner_01"},
  {champion:"Aurelion Sol",r1:"Starforged Gauntlets",r2:"Oath of the Guardians",r3:"Guardian's Trinket",star:"4*-40",player:"u/Yorusluti"},
  // ── Azir ──
  {champion:"Azir",r1:"Disciple of Shadows",r2:"Succubus's Brand",r3:"Crownguard Inheritance",star:"6*-33",player:"jewl, Bushi"},
  {champion:"Azir",r1:"Echoing Spirit",r2:"Condenser",r3:"Star Gem",star:"6*-47",player:"HPDARK"},
  {champion:"Azir",r1:"Fear-Cleaving Axe",r2:"Found Fortune",r3:"Chosen by the Stars",star:"6*-38",player:"Nuimee"},
  {champion:"Azir",r1:"Fear-Cleaving Axe",r2:"Found Fortune",r3:"Star Gem",star:"6*-39",player:"u/TaskRabbit14"},
  {champion:"Azir",r1:"Azir's Staff of Office",r2:"Scales of Judgement",r3:"Star Gem",star:"6*-35",player:"TwoStickmen"},
  {champion:"Azir",r1:"The Beast Within",r2:"Fear-Cleaving Axe",r3:"Star Gem",star:"6*-42",player:"u/Cyphren"},
  {champion:"Azir",r1:"Chosen by the Stars",r2:"Star Gem",r3:"Star Gem",star:"5*-38",player:"Nazoric"},
  {champion:"Azir",r1:"Oath of the Guardians",r2:"Star Gem",r3:"Star Gem",star:"6*-42",player:"u/DizzyDoesDallas, u/Airtnp, Chengsta"},
  {champion:"Azir",r1:"Stalker's Blade",r2:"Star Gem",r3:"Star Gem",star:"6*-36",player:"BlackPolarBear"},
  {champion:"Azir",r1:"Crownguard Inheritance",r2:"Star Gem",r3:"Star Gem",star:"6*-50",player:"Hooded, ProfSE, aoeuid"},
  // ── Caitlyn ──
  {champion:"Caitlyn",r1:"Deadly Harpoon",r2:"Hidden Tome",r3:"The Beast Within",star:"6*-44",player:"powercuties"},
  {champion:"Caitlyn",r1:"Mischiefmaker's Flute",r2:"Guardian Angel",r3:"Harmless Scarecrow",star:"6*-42",player:"RoloRolla"},
  {champion:"Caitlyn",r1:"Death's Foil",r2:"Harmless Scarecrow",r3:"Mischiefmaker's Flute",star:"6*-39",player:"Nazoric"},
  {champion:"Caitlyn",r1:"Hextech Rifle",r2:"Harmless Scarecrow",r3:"Mischiefmaker's Flute",star:"6*-50",player:"LehmonNation"},
  {champion:"Caitlyn",r1:"Hextech Rifle",r2:"Harmless Scarecrow",r3:"Hidden Tome",star:"6*-50",player:"cyclonus101, ProfSE"},
  {champion:"Caitlyn",r1:"Hextech Rifle",r2:"Harmless Scarecrow",r3:"Echoing Spirit",star:"4*-50",player:"Zarkkast, TwoStickmen"},
  {champion:"Caitlyn",r1:"Hextech Rifle",r2:"Guardian Angel",r3:"Voidborne Carapace",star:"4*-36",player:"Katisu"},
  {champion:"Caitlyn",r1:"Stalker's Blade",r2:"Guardian Angel",r3:"Voidborne Carapace",star:"6*-40",player:"BumpyRoad"},
  {champion:"Caitlyn",r1:"Stalker's Blade",r2:"Guardian Angel",r3:"Guardian Angel",star:"6*-36",player:"Erian"},
  // ── Darius ──
  {champion:"Darius",r1:"Starforged Gauntlets",r2:"The Hand of Noxus",r3:"Stacked Deck",star:"6*-35",player:"u/dt_again"},
  {champion:"Darius",r1:"Starforged Gauntlets",r2:"The Hand of Noxus",r3:"Corrupted Star Fragment",star:"6*-41",player:"Nazoric"},
  {champion:"Darius",r1:"Starforged Gauntlets",r2:"Spectral Scissors",r3:"Loaded Dice",star:"5*-33",player:"Mike Hamster"},
  {champion:"Darius",r1:"Chosen by the Stars",r2:"Disciple of Shadows",r3:"Lux's Incandescent Baton",star:"6*-40",player:"HPDARK"},
  {champion:"Darius",r1:"Loaded Dice",r2:"Z-Drive Prototype",r3:"Z-Drive Prototype",star:"6*-50",player:"Hooded, ProfSE, baseball7000"},
  {champion:"Darius",r1:"Loaded Dice",r2:"Black Shield",r3:"Z-Drive Prototype",star:"6*-50",player:"cyclonus101"},
  // ── Diana ──
  {champion:"Diana",r1:"Chosen by the Stars",r2:"Echoing Spirit",r3:"Searing Brilliance",star:"3*-36",player:"Nazoric"},
  // ── Ekko ──
  {champion:"Ekko",r1:"Echoing Spirit",r2:"Chosen by the Stars",r3:"Searing Brilliance",star:"4*-34",player:"aoeuid, ProfSE, Nazoric"},
  {champion:"Ekko",r1:"Echoing Spirit",r2:"Chosen by the Stars",r3:"Hidden Tome",star:"6*-35",player:"HPDARK"},
  {champion:"Ekko",r1:"Echoing Spirit",r2:"Death's Foil",r3:"Found Fortune",star:"6*-50",player:"u/legner_01"},
  {champion:"Ekko",r1:"Echoing Spirit",r2:"Guardian's Orb",r3:"Guardian's Orb",star:"5*-44",player:"u/Miro_miro23, Kit Cat"},
  {champion:"Ekko",r1:"Echoing Spirit",r2:"Harmless Scarecrow",r3:"Makeshift Mayhem",star:"4*-33",player:"VodopadUmraza"},
  {champion:"Ekko",r1:"Echoing Spirit",r2:"Stalker's Blade",r3:"The Grand General's Counterplan",star:"6*-37",player:"The Moral Support"},
  {champion:"Ekko",r1:"Echoing Spirit",r2:"Stalker's Blade",r3:"Stalker's Blade",star:"6*-50",player:"cyclonus101"},
  {champion:"Ekko",r1:"The Chameleon's Necklace",r2:"Stalker's Blade",r3:"Stalker's Blade",star:"6*-33",player:"Mike Hamster"},
  {champion:"Ekko",r1:"Oath of the Guardians",r2:"Scales of Judgement",r3:"Star Gem",star:"6*-37",player:"TwoStickmen"},
  {champion:"Ekko",r1:"Searing Brilliance",r2:"The Beast Within",r3:"Disciple of Shadows",star:"6*-50",player:"LehmonNation"},
  // ── Elder Dragon ──
  {champion:"Elder Dragon",r1:"Disciple of Shadows",r2:"Portal Pals",r3:"Black Shield",star:"6*-38",player:"u/Simonirico"},
  {champion:"Elder Dragon",r1:"Starforged Gauntlets",r2:"Secret Technique",r3:"Hymn of Valor",star:"6*-47",player:"HPDARK"},
  {champion:"Elder Dragon",r1:"Starforged Gauntlets",r2:"Great Talons",r3:"Emotional Support Bear",star:"6*-39",player:"Nazoric"},
  {champion:"Elder Dragon",r1:"Starforged Gauntlets",r2:"The Beast Within",r3:"Black Shield",star:"6*-41",player:"u/Katisurinkai"},
  {champion:"Elder Dragon",r1:"Starforged Gauntlets",r2:"Portal Pals",r3:"Found Fortune",star:"6*-42",player:"u/TurkeyBuzzard04"},
  {champion:"Elder Dragon",r1:"Starforged Gauntlets",r2:"Portal Pals",r3:"Black Shield",star:"6*-50",player:"xopuxir, Erian"},
  {champion:"Elder Dragon",r1:"Starforged Gauntlets",r2:"Portal Pals",r3:"Loaded Dice",star:"6*-47",player:"HPDARK"},
  {champion:"Elder Dragon",r1:"Starforged Gauntlets",r2:"The Beast Within",r3:"Cease and Desist",star:"6*-50",player:"cyclonus101, Magnum Flare, yuemoonn"},
  {champion:"Elder Dragon",r1:"Starforged Gauntlets",r2:"Essence Theft",r3:"Cease and Desist",star:"6*-50",player:"Sydiem"},
  {champion:"Elder Dragon",r1:"Stalker's Blade",r2:"Stalker's Blade",r3:"The Curator's Gatebreaker",star:"6*-38",player:"tomyang1117"},
  // ── Elise ──
  {champion:"Elise",r1:"Fear-Cleaving Axe",r2:"Cruel Experiments",r3:"Galeforce",star:"4*-42",player:"Huffy, baseball7000"},
  {champion:"Elise",r1:"Fear-Cleaving Axe",r2:"Galeforce",r3:"Dreams Of Yordles",star:"6*-37",player:"RoloRolla, kingarkal"},
  {champion:"Elise",r1:"Echoing Spirit",r2:"Galeforce",r3:"Dreams Of Yordles",star:"5*-30",player:"Catamarano"},
  {champion:"Elise",r1:"Echoing Spirit",r2:"Fear-Cleaving Axe",r3:"Galeforce",star:"5*-42",player:"u/MinhTrocs"},
  {champion:"Elise",r1:"Echoing Spirit",r2:"Voidborne Carapace",r3:"Dreams Of Yordles",star:"6*-43",player:"K0zt"},
  {champion:"Elise",r1:"Full Build",r2:"Voidborne Carapace",r3:"Dreams Of Yordles",star:"5*-44",player:"Chaney"},
  {champion:"Elise",r1:"Found Fortune",r2:"Voidborne Carapace",r3:"Corrupted Star Fragment",star:"5*-44",player:"aoeuid, jewl, Sliverz"},
  {champion:"Elise",r1:"Found Fortune",r2:"Galeforce",r3:"Dreams Of Yordles",star:"5*-40",player:"HPDARK"},
  {champion:"Elise",r1:"Spirit of the Buhru",r2:"Galeforce",r3:"Dreams Of Yordles",star:"6*-39",player:"u/Katisurinkai"},
  {champion:"Elise",r1:"Queen's Embrace",r2:"Death's Foil",r3:"Voidborne Carapace",star:"6*-43",player:"Nazoric"},
  {champion:"Elise",r1:"Queen's Embrace",r2:"Found Fortune",r3:"Corrupted Star Fragment",star:"5*-50",player:"Hooded, cyclonus101, SSJ5GOKU"},
  {champion:"Elise",r1:"Queen's Embrace",r2:"Fear-Cleaving Axe",r3:"Galeforce",star:"6*-40",player:"u/TaskRabbit14"},
  {champion:"Elise",r1:"Queen's Embrace",r2:"Death's Foil",r3:"Galeforce",star:"6*-39",player:"Mike Hamster"},
  {champion:"Elise",r1:"Queen's Embrace",r2:"Echoing Spirit",r3:"Galeforce",star:"6*-50",player:"The Doomba"},
  {champion:"Elise",r1:"Queen's Embrace",r2:"Full Build",r3:"Galeforce",star:"6*-50",player:"u/Airtnp, u/Met2003"},
  // ── Evelynn ──
  {champion:"Evelynn",r1:"Swain's Raven Army",r2:"Packed Powder",r3:"Found Fortune",star:"5*-35",player:"Nazoric"},
  {champion:"Evelynn",r1:"Swain's Raven Army",r2:"Packed Powder",r3:"Echoing Spirit",star:"3*-35",player:"VodopadUmraza"},
  {champion:"Evelynn",r1:"Echoing Spirit",r2:"Succubus's Brand",r3:"Tempest Blade",star:"6*-49",player:"ProfSE"},
  {champion:"Evelynn",r1:"Starforged Gauntlets",r2:"Luminous Orb",r3:"Tempest Blade",star:"6*-36",player:"HPDARK"},
  {champion:"Evelynn",r1:"Disciple of Shadows",r2:"Crownguard Inheritance",r3:"Tempest Blade",star:"5*-35",player:"Hooded, BumpyRoad, The Moral Support"},
  {champion:"Evelynn",r1:"Disciple of Shadows",r2:"Stacked Deck",r3:"Tempest Blade",star:"3*-34",player:"Huffy"},
  {champion:"Evelynn",r1:"Siren's Call",r2:"Jayce's Hextech Battery",r3:"Tempest Blade",star:"6*-39",player:"TwoStickmen"},
  {champion:"Evelynn",r1:"Siren's Call",r2:"Black Shield",r3:"Tempest Blade",star:"6*-45",player:"u/Akazaka_"},
  // ── Fiddlesticks ──
  {champion:"Fiddlesticks",r1:"Harmless Scarecrow",r2:"Norra's Portal Accelerator",r3:"Shock & Awe",star:"6*-41",player:"yuemoonn, Chengsta"},
  {champion:"Fiddlesticks",r1:"The Chameleon's Necklace",r2:"Shock & Awe",r3:"Loaded Dice",star:"6*-41",player:"u/Yorusluti"},
  {champion:"Fiddlesticks",r1:"Echoing Spirit",r2:"Harmless Scarecrow",r3:"Loaded Dice",star:"6*-43",player:"K0zt, TwoStickmen"},
  {champion:"Fiddlesticks",r1:"Echoing Spirit",r2:"Archangel's Staff",r3:"Chemtech Duplicator",star:"6*-49",player:"u/Syokhan"},
  {champion:"Fiddlesticks",r1:"Echoing Spirit",r2:"Harmless Scarecrow",r3:"Chemtech Duplicator",star:"6*-50",player:"Hooded, cyclonus101, ProfSE, Nazoric"},
  {champion:"Fiddlesticks",r1:"Echoing Spirit",r2:"Shock & Awe",r3:"Loaded Dice",star:"6*-50",player:"u/dt_again, u/Airtnp"},
  {champion:"Fiddlesticks",r1:"Harmless Scarecrow",r2:"Loaded Dice",r3:"Essence Theft",star:"6*-50",player:"Sydiem"},
  {champion:"Fiddlesticks",r1:"Loaded Dice",r2:"Z-Drive Prototype",r3:"Z-Drive Prototype",star:"6*-50",player:"HPDARK"},
  {champion:"Fiddlesticks",r1:"Harmless Scarecrow",r2:"Loaded Dice",r3:"Shock & Awe",star:"6*-50",player:"jewl, u/Met2003"},
  // ── Garen ──
  {champion:"Garen",r1:"Black Shield",r2:"The Grand General's Counterplan",r3:"Voidborne Carapace",star:"3*-43",player:"Suurkyy"},
  // ── Gwen ──
  {champion:"Gwen",r1:"Disciple of Shadows",r2:"Guardian Angel",r3:"Voidborne Carapace",star:"6*-45",player:"u/mrshmllwzz"},
  {champion:"Gwen",r1:"Disciple of Shadows",r2:"Black Shield",r3:"Voidborne Carapace",star:"6*-35",player:"Catamarano"},
  {champion:"Gwen",r1:"Disciple of Shadows",r2:"Death's Foil",r3:"Black Shield",star:"6*-47",player:"lolguy999"},
  {champion:"Gwen",r1:"Disciple of Shadows",r2:"Death's Foil",r3:"Draconic Runes",star:"6*-41",player:"Nazoric"},
  {champion:"Gwen",r1:"Disciple of Shadows",r2:"Chosen by the Stars",r3:"Spirit of the Buhru",star:"6*-48",player:"HPDARK"},
  {champion:"Gwen",r1:"Disciple of Shadows",r2:"Echoing Spirit",r3:"Galeforce",star:"6*-38",player:"TwoStickmen"},
  {champion:"Gwen",r1:"Disciple of Shadows",r2:"Found Fortune",r3:"Corrupted Star Fragment",star:"6*-50",player:"cyclonus101, ProfSE"},
  {champion:"Gwen",r1:"Galeforce",r2:"Wicked Harvest",r3:"Luden's Tempest",star:"6*-50",player:"vv"},
  // ── Heimerdinger ──
  {champion:"Heimerdinger",r1:"Defense Spending",r2:"Packed Powder",r3:"Swain's Raven Army",star:"6*-50",player:"NarvalDream, Nazoric"},
  {champion:"Heimerdinger",r1:"Defense Spending",r2:"Disciple of Shadows",r3:"Chemtech Duplicator",star:"6*-49",player:"u/Dangerous_Switch_716"},
  {champion:"Heimerdinger",r1:"The Beast Within",r2:"Disciple of Shadows",r3:"Jayce's Hextech Battery",star:"6*-39",player:"TwoStickmen"},
  {champion:"Heimerdinger",r1:"The Beast Within",r2:"Disciple of Shadows",r3:"Black Shield",star:"6*-50",player:"Hera"},
  {champion:"Heimerdinger",r1:"The Beast Within",r2:"Disciple of Shadows",r3:"Loaded Dice",star:"6*-50",player:"Hooded, ProfSE"},
  {champion:"Heimerdinger",r1:"The Beast Within",r2:"Loaded Dice",r3:"Arcane Comet",star:"6*-41",player:"Katisu"},
  {champion:"Heimerdinger",r1:"Starforged Gauntlets",r2:"Luminous Orb",r3:"Jayce's Hextech Battery",star:"6*-50",player:"cyclonus101"},
  // ── Jack ──
  {champion:"Jack",r1:"Chosen by the Stars",r2:"Hidden Tome",r3:"Death's Foil",star:"3*-45",player:"Suurkyy"},
  // ── Jayce ──
  {champion:"Jayce",r1:"Jayce's Hextech Battery",r2:"Protectors of Demacia",r3:"Chemtech Duplicator",star:"5*-36",player:"Nazoric"},
  {champion:"Jayce",r1:"Jayce's Hextech Battery",r2:"Loaded Dice",r3:"Chemtech Duplicator",star:"6*-45",player:"HPDARK, ProfSE, TwoStickmen"},
  {champion:"Jayce",r1:"Jayce's Hextech Battery",r2:"Renewing Power",r3:"Chemtech Duplicator",star:"6*-48",player:"HPDARK"},
  {champion:"Jayce",r1:"Jayce's Hextech Battery",r2:"The Grand General's Counterplan",r3:"Chemtech Duplicator",star:"6*-50",player:"u/Cyphren"},
  {champion:"Jayce",r1:"Frozen Tomb",r2:"Hidden Tome",r3:"Chemtech Duplicator",star:"3*-35",player:"VodopadUmraza"},
  {champion:"Jayce",r1:"Stacked Deck",r2:"Loaded Dice",r3:"Chemtech Duplicator",star:"6*-50",player:"cyclonus101"},
  {champion:"Jayce",r1:"Archangel's Staff",r2:"Arcane Comet",r3:"Chemtech Duplicator",star:"6*-35",player:"The Moral Support"},
  // ── Jhin ──
  {champion:"Jhin",r1:"The Curator's Gatebreaker",r2:"Riptide Battery",r3:"Cease and Desist",star:"5*-37",player:"Catamarano, RoloRolla"},
  {champion:"Jhin",r1:"The Curator's Gatebreaker",r2:"Riptide Battery",r3:"Whisper",star:"6*-50",player:"u/Airtnp, TwoStickmen"},
  {champion:"Jhin",r1:"The Curator's Gatebreaker",r2:"Riptide Battery",r3:"Big Guns",star:"6*-42",player:"Chengsta"},
  {champion:"Jhin",r1:"Riptide Battery",r2:"Riptide Battery",r3:"Cease and Desist",star:"6*-35",player:"HPDARK"},
  {champion:"Jhin",r1:"The Curator's Gatebreaker",r2:"Riptide Battery",r3:"Riptide Battery",star:"3*-37",player:"VodopadUmraza"},
  {champion:"Jhin",r1:"Deck of Destiny",r2:"Riptide Battery",r3:"Riptide Battery",star:"6*-40",player:"jewl"},
  {champion:"Jhin",r1:"Deck of Destiny",r2:"Riptide Battery",r3:"Big Guns",star:"6*-50",player:"u/legner_01, Nazoric"},
  {champion:"Jhin",r1:"Deck of Destiny",r2:"Riptide Battery",r3:"Cease and Desist",star:"6*-50",player:"LehmonNation, PetiB, ProfSE"},
  {champion:"Jhin",r1:"Searing Brilliance",r2:"Hidden Tome",r3:"Chosen by the Stars",star:"4*-36",player:"aoeuid"},
  // ── Jinx ──
  {champion:"Jinx",r1:"The Loose Cannon's Payload",r2:"Guardian Angel",r3:"The Scourge's Stash",star:"3*-48",player:"diaversai, Mike Hamster"},
  {champion:"Jinx",r1:"Loaded Dice",r2:"The Loose Cannon's Payload",r3:"Guardian Angel",star:"4*-50",player:"Alex"},
  {champion:"Jinx",r1:"Packed Powder",r2:"The Loose Cannon's Payload",r3:"Guardian Angel",star:"5*-36",player:"Catamarano, Yuemoonn"},
  {champion:"Jinx",r1:"Disciple of Shadows",r2:"The Loose Cannon's Payload",r3:"Guardian Angel",star:"5*-41",player:"Huffy"},
  {champion:"Jinx",r1:"Disciple of Shadows",r2:"The Loose Cannon's Payload",r3:"The Grand General's Counterplan",star:"6*-33",player:"HPDARK, Sliverz"},
  {champion:"Jinx",r1:"Loaded Dice",r2:"The Loose Cannon's Payload",r3:"The Grand General's Counterplan",star:"6*-37",player:"u/ChingChong-100"},
  {champion:"Jinx",r1:"Big Guns",r2:"The Loose Cannon's Payload",r3:"The Grand General's Counterplan",star:"6*-50",player:"cyclonus101"},
  {champion:"Jinx",r1:"Searing Brilliance",r2:"The Loose Cannon's Payload",r3:"The Grand General's Counterplan",star:"6*-50",player:"Bushi, baseball7000"},
  {champion:"Jinx",r1:"Searing Brilliance",r2:"The Loose Cannon's Payload",r3:"Guardian Angel",star:"4*-39",player:"aoeuid"},
  {champion:"Jinx",r1:"Searing Brilliance",r2:"Packed Powder",r3:"The Loose Cannon's Payload",star:"6*-42",player:"Magnum Flare"},
  {champion:"Jinx",r1:"Deck of Destiny",r2:"Searing Brilliance",r3:"Big Guns",star:"5*-36",player:"Nazoric"},
  {champion:"Jinx",r1:"Guardian Angel",r2:"Guardian Angel",r3:"The Loose Cannon's Payload",star:"6*-50",player:"Hooded"},
  {champion:"Jinx",r1:"Essence Theft",r2:"The Loose Cannon's Payload",r3:"Guardian Angel",star:"6*-50",player:"Sydiem"},
  {champion:"Jinx",r1:"Echoing Spirit",r2:"The Loose Cannon's Payload",r3:"The Grand General's Counterplan",star:"6*-50",player:"Help, ProfSE"},
  // ── Kai'Sa ──
  {champion:"Kai'Sa",r1:"Chosen by the Stars",r2:"Full Build",r3:"Loaded Dice",star:"6*-37",player:"HPDARK"},
  {champion:"Kai'Sa",r1:"Black Shield",r2:"The Beast Within",r3:"Dreams Of Yordles",star:"6*-50",player:"cyclonus101"},
  {champion:"Kai'Sa",r1:"Perfect Hex Core",r2:"Black Shield",r3:"Galeforce",star:"6*-34",player:"u/Cyphren"},
  {champion:"Kai'Sa",r1:"Perfect Hex Core",r2:"Luden's Tempest",r3:"Dreams Of Yordles",star:"6*-39",player:"xopuxir"},
  {champion:"Kai'Sa",r1:"Perfect Hex Core",r2:"Chosen by the Stars",r3:"Dreams Of Yordles",star:"6*-50",player:"LehmonNation"},
  {champion:"Kai'Sa",r1:"Perfect Hex Core",r2:"Chosen by the Stars",r3:"Black Shield",star:"6*-38",player:"yuemoonn"},
  {champion:"Kai'Sa",r1:"Perfect Hex Core",r2:"Chosen by the Stars",r3:"Queen's Embrace",star:"6*-39",player:"Hooded, Nazoric"},
  {champion:"Kai'Sa",r1:"Perfect Hex Core",r2:"Full Build",r3:"Queen's Embrace",star:"6*-33",player:"u/TaskRabbit14"},
  {champion:"Kai'Sa",r1:"Perfect Hex Core",r2:"Full Build",r3:"Dreams Of Yordles",star:"6*-45",player:"RoloRolla, ProfSE"},
  // ── Kayle ──
  {champion:"Kayle",r1:"Loaded Dice",r2:"Z-Drive Prototype",r3:"Z-Drive Prototype",star:"6*-35",player:"baseball7000"},
  {champion:"Kayle",r1:"Spellweaver's Symphony",r2:"Cease and Desist",r3:"Secret Technique",star:"6*-36",player:"Nazoric"},
  {champion:"Kayle",r1:"Secret Technique",r2:"Loaded Dice",r3:"Z-Drive Prototype",star:"6*-50",player:"Hooded"},
  {champion:"Kayle",r1:"Starfire Spellblade",r2:"Loaded Dice",r3:"Found Fortune",star:"6*-50",player:"Bushi"},
  {champion:"Kayle",r1:"Starfire Spellblade",r2:"Loaded Dice",r3:"Secret Technique",star:"6*-50",player:"cyclonus101, ProfSE"},
  // ── LeBlanc ──
  {champion:"LeBlanc",r1:"Stalker's Blade",r2:"Stalker's Blade",r3:"Stalker's Blade",star:"3*-43",player:"Lau"},
  // ── Leona ──
  {champion:"Leona",r1:"Swain's Raven Army",r2:"Packed Powder",r3:"Found Fortune",star:"6*-37",player:"Nazoric"},
  {champion:"Leona",r1:"Found Fortune",r2:"Starforged Gauntlets",r3:"Luminous Orb",star:"6*-35",player:"cyclonus101"},
  {champion:"Leona",r1:"Echoing Spirit",r2:"Found Fortune",r3:"Disciple of Shadows",star:"6*-50",player:"Hooded, Chengsta"},
  {champion:"Leona",r1:"Echoing Spirit",r2:"Found Fortune",r3:"Loaded Dice",star:"6*-50",player:"TwoStickmen"},
  {champion:"Leona",r1:"Echoing Spirit",r2:"Found Fortune",r3:"Perfect Hex Core",star:"6*-50",player:"ProfSE"},
  // ── Lillia ──
  {champion:"Lillia",r1:"Guardian's Orb",r2:"Guardian's Orb",r3:"Stalker's Blade",star:"5*-40",player:"2ndTony"},
  {champion:"Lillia",r1:"Stalker's Blade",r2:"Stalker's Blade",r3:"Everfrost",star:"4*-35",player:"kingarkal"},
  {champion:"Lillia",r1:"Echoing Spirit",r2:"Guardian's Orb",r3:"Everfrost",star:"6*-42",player:"RoloRolla"},
  {champion:"Lillia",r1:"Echoing Spirit",r2:"Stalker's Blade",r3:"Spirit Forge",star:"6*-34",player:"HPDARK"},
  {champion:"Lillia",r1:"Echoing Spirit",r2:"Guardian's Orb",r3:"Guardian's Orb",star:"6*-50",player:"cyclonus101, baseball7000"},
  {champion:"Lillia",r1:"Echoing Spirit",r2:"Stalker's Blade",r3:"Stalker's Blade",star:"6*-50",player:"ProfSE, BumpyRoad, aoeuid"},
  {champion:"Lillia",r1:"Echoing Spirit",r2:"The Taker's Bow",r3:"Guardian's Orb",star:"6*-36",player:"Nazoric, TwoStickmen"},
  {champion:"Lillia",r1:"Hidden Tome",r2:"Guardian's Orb",r3:"Guardian's Orb",star:"6*-37",player:"Katisu"},
  {champion:"Lillia",r1:"Wicked Harvest",r2:"Stalker's Blade",r3:"Guardian Angel",star:"3*-34",player:"Huffy"},
  // ── Lux ──
  {champion:"Lux",r1:"Frozen Tomb",r2:"Arcane Comet",r3:"Chemtech Duplicator",star:"6*-38",player:"lolguy999"},
  {champion:"Lux",r1:"Lux's Incandescent Baton",r2:"Arcane Comet",r3:"Chemtech Duplicator",star:"6*-50",player:"cyclonus101, u/Katisurinkai, Nazoric"},
  {champion:"Lux",r1:"Lux's Incandescent Baton",r2:"Hidden Tome",r3:"Chemtech Duplicator",star:"6*-50",player:"Tangolino, Huffy, TwoStickmen"},
  {champion:"Lux",r1:"Lux's Incandescent Baton",r2:"Packed Powder",r3:"Chemtech Duplicator",star:"6*-50",player:"u/Airtnp"},
  {champion:"Lux",r1:"Lux's Incandescent Baton",r2:"Chemtech Duplicator",r3:"Frozen Tomb",star:"6*-50",player:"Hooded"},
  // ── Lux: Illuminated ──
  {champion:"Lux: Illuminated",r1:"Lux's Incandescent Baton",r2:"Voidborne Carapace",r3:"Wicked Harvest",star:"4*-36",player:"Huffy"},
  {champion:"Lux: Illuminated",r1:"Lux's Incandescent Baton",r2:"Found Fortune",r3:"Crownguard Inheritance",star:"6*-35",player:"Hooded, TwoStickmen"},
  {champion:"Lux: Illuminated",r1:"Lux's Incandescent Baton",r2:"Fear-Cleaving Axe",r3:"Found Fortune",star:"5*-38",player:"HPDARK, Nazoric, cyclonus101"},
  {champion:"Lux: Illuminated",r1:"Lux's Incandescent Baton",r2:"Fear-Cleaving Axe",r3:"Perfect Hex Core",star:"6*-37",player:"u/TaskRabbit14"},
  {champion:"Lux: Illuminated",r1:"Found Fortune",r2:"Fear-Cleaving Axe",r3:"Hidden Tome",star:"6*-38",player:"Katisu"},
  // ── Master Yi ──
  {champion:"Master Yi",r1:"Chosen by the Stars",r2:"Echoing Spirit",r3:"Secret Technique",star:"3*-36",player:"Chengsta"},
  // ── Mel ──
  {champion:"Mel",r1:"Voidborne Carapace",r2:"Guardian Angel",r3:"Wicked Harvest",star:"3*-33",player:"Sions Jawline"},
  {champion:"Mel",r1:"Voidborne Carapace",r2:"Guardian Angel",r3:"Guardian Angel",star:"3*-37",player:"diaversai, kingarkal"},
  {champion:"Mel",r1:"Voidborne Carapace",r2:"Guardian Angel",r3:"Loaded Dice",star:"4*-39",player:"HPDARK, Mike Hamster"},
  {champion:"Mel",r1:"Found Fortune",r2:"Hidden Tome",r3:"Searing Brilliance",star:"6*-50",player:"Sydiem"},
  {champion:"Mel",r1:"Echoing Spirit",r2:"Hidden Tome",r3:"Searing Brilliance",star:"6*-37",player:"Nazoric, cyclonus101, Katisu"},
  {champion:"Mel",r1:"Echoing Spirit",r2:"Hidden Tome",r3:"Perfect Hex Core",star:"6*-40",player:"u/Cindrojn"},
  {champion:"Mel",r1:"Echoing Spirit",r2:"Hidden Tome",r3:"Big Guns",star:"3*-35",player:"VodopadUmraza"},
  {champion:"Mel",r1:"Echoing Spirit",r2:"Hidden Tome",r3:"The Grand General's Counterplan",star:"4*-39",player:"Zarkkast"},
  {champion:"Mel",r1:"Echoing Spirit",r2:"Hidden Tome",r3:"Guardian Angel",star:"4*-37",player:"K0zt"},
  {champion:"Mel",r1:"Echoing Spirit",r2:"Searing Brilliance",r3:"Guardian Angel",star:"6*-42",player:"TwoStickmen"},
  {champion:"Mel",r1:"Echoing Spirit",r2:"Archangel's Staff",r3:"The Grand General's Counterplan",star:"6*-36",player:"Erian"},
  {champion:"Mel",r1:"Echoing Spirit",r2:"Archangel's Staff",r3:"Luden's Tempest",star:"6*-35",player:"The Moral Support"},
  {champion:"Mel",r1:"Echoing Spirit",r2:"Guardian Angel",r3:"Voidborne Carapace",star:"6*-50",player:"ProfSE"},
  // ── Miss Fortune ──
  {champion:"Miss Fortune",r1:"Echoing Spirit",r2:"The Grand General's Counterplan",r3:"Guardian Angel",star:"6*-45",player:"HPDARK"},
  {champion:"Miss Fortune",r1:"Echoing Spirit",r2:"The Grand General's Counterplan",r3:"Searing Brilliance",star:"6*-50",player:"ProfSE, yuemoonn"},
  {champion:"Miss Fortune",r1:"Echoing Spirit",r2:"Big Guns",r3:"Searing Brilliance",star:"6*-38",player:"Nazoric"},
  {champion:"Miss Fortune",r1:"Big Guns",r2:"Searing Brilliance",r3:"The Grand General's Counterplan",star:"5*-36",player:"Yatotoro"},
  {champion:"Miss Fortune",r1:"Deck of Destiny",r2:"Shock & Awe",r3:"Searing Brilliance",star:"4*-36",player:"Mike Hamster"},
  {champion:"Miss Fortune",r1:"Deck of Destiny",r2:"Shock & Awe",r3:"The Beast Within",star:"6*-50",player:"Bushi"},
  // ── Mordekaiser ──
  {champion:"Mordekaiser",r1:"Disciple of Shadows",r2:"Guardian Angel",r3:"Voidborne Carapace",star:"3*-49",player:"Suurkyy"},
  // ── Morgana ──
  {champion:"Morgana",r1:"Echoing Spirit",r2:"Searing Brilliance",r3:"The Beast Within",star:"6*-35",player:"Nazoric"},
  {champion:"Morgana",r1:"Echoing Spirit",r2:"Searing Brilliance",r3:"Chemtech Duplicator",star:"4*-37",player:"aoeuid"},
  {champion:"Morgana",r1:"Echoing Spirit",r2:"Hidden Tome",r3:"The Grand General's Counterplan",star:"5*-50",player:"PetiB"},
  {champion:"Morgana",r1:"Echoing Spirit",r2:"Searing Brilliance",r3:"The Grand General's Counterplan",star:"6*-50",player:"ProfSE"},
  {champion:"Morgana",r1:"Echoing Spirit",r2:"Loaded Dice",r3:"The Grand General's Counterplan",star:"5*-40",player:"jewl"},
  {champion:"Morgana",r1:"Archangel's Staff",r2:"Loaded Dice",r3:"The Grand General's Counterplan",star:"4*-38",player:"the yapper"},
  {champion:"Morgana",r1:"Archangel's Staff",r2:"The Grand General's Counterplan",r3:"Wicked Harvest",star:"5*-33",player:"diaversai"},
  {champion:"Morgana",r1:"Chosen by the Stars",r2:"The Grand General's Counterplan",r3:"Chemtech Duplicator",star:"4*-41",player:"Aizen"},
  {champion:"Morgana",r1:"Chosen by the Stars",r2:"Hymn of Valor",r3:"Chemtech Duplicator",star:"6*-36",player:"Erian"},
  {champion:"Morgana",r1:"Chosen by the Stars",r2:"Hidden Tome",r3:"Deck of Destiny",star:"6*-33",player:"TwoStickmen"},
  // ── Nasus ──
  {champion:"Nasus",r1:"Scales of Judgement",r2:"Starfire Spellblade",r3:"Starforged Gauntlets",star:"6*-37",player:"Nazoric"},
  {champion:"Nasus",r1:"Chosen by the Stars",r2:"Disciple of Shadows",r3:"Wicked Harvest",star:"6*-40",player:"Huffy, Catamarano"},
  {champion:"Nasus",r1:"Chosen by the Stars",r2:"Echoing Spirit",r3:"The Grand General's Counterplan",star:"6*-44",player:"u/kosheiry, PetiB"},
  {champion:"Nasus",r1:"Disciple of Shadows",r2:"Echoing Spirit",r3:"The Grand General's Counterplan",star:"6*-41",player:"u/Wizard_Volovik"},
  {champion:"Nasus",r1:"Scales of Judgement",r2:"The Beast Within",r3:"Oath of the Guardians",star:"6*-50",player:"Magnum Flare, ProfSE"},
  {champion:"Nasus",r1:"Scales of Judgement",r2:"The Beast Within",r3:"Cease and Desist",star:"6*-35",player:"TwoStickmen"},
  {champion:"Nasus",r1:"Wicked Harvest",r2:"Voidborne Carapace",r3:"The Grand General's Counterplan",star:"6*-33",player:"Mike Hamster"},
  // ── Nautilus ──
  {champion:"Nautilus",r1:"Starforged Gauntlets",r2:"Searing Brilliance",r3:"The Beast Within",star:"5*-36",player:"Nazoric, aoeuid"},
  {champion:"Nautilus",r1:"Starforged Gauntlets",r2:"The Beast Within",r3:"Fate's Hand",star:"6*-40",player:"TwoStickmen"},
  {champion:"Nautilus",r1:"Starforged Gauntlets",r2:"Stacked Deck",r3:"The Beast Within",star:"6*-36",player:"QV, PetiB, Hooded"},
  {champion:"Nautilus",r1:"Starforged Gauntlets",r2:"Stacked Deck",r3:"Treasures of the Deep",star:"6*-41",player:"Nuimee"},
  {champion:"Nautilus",r1:"Starforged Gauntlets",r2:"Stacked Deck",r3:"Searing Brilliance",star:"6*-49",player:"LehmonNation, ProfSE"},
  {champion:"Nautilus",r1:"The Beast Within",r2:"Stacked Deck",r3:"Heart of Gold",star:"6*-36",player:"The Moral Support"},
  // ── Neeko ──
  {champion:"Neeko",r1:"Echoing Spirit",r2:"Dreadway Chase Gun",r3:"Ravenous Hydra",star:"4*-33",player:"Huffy"},
  {champion:"Neeko",r1:"Echoing Spirit",r2:"Found Fortune",r3:"Loaded Dice",star:"5*-34",player:"HPDARK"},
  {champion:"Neeko",r1:"Echoing Spirit",r2:"The Beast Within",r3:"Death's Foil",star:"6*-40",player:"Nazoric"},
  {champion:"Neeko",r1:"Echoing Spirit",r2:"The Beast Within",r3:"Fear-Cleaving Axe",star:"6*-50",player:"cyclonus101, Catamarano, Hooded"},
  {champion:"Neeko",r1:"Echoing Spirit",r2:"Searing Brilliance",r3:"Guardian's Orb",star:"6*-50",player:"LehmonNation, ProfSE, diaversai"},
  // ── Norra ──
  {champion:"Norra",r1:"Scales of Judgement",r2:"Echoing Spirit",r3:"Hidden Tome",star:"6*-50",player:"LehmonNation, Hooded, ProfSE"},
  {champion:"Norra",r1:"Scales of Judgement",r2:"The Beast Within",r3:"Stacked Deck",star:"5*-50",player:"Nazoric"},
  {champion:"Norra",r1:"Norra's Portal Accelerator",r2:"The Beast Within",r3:"Stacked Deck",star:"5*-50",player:"cyclonus101"},
  // ── Nunu & Willump ──
  {champion:"Nunu & Willump",r1:"Guardian's Orb",r2:"Guardian Angel",r3:"Voidborne Carapace",star:"5*-34",player:"HPDARK, LehmonNation"},
  {champion:"Nunu & Willump",r1:"Yeti Spotting Guide",r2:"Guardian Angel",r3:"Voidborne Carapace",star:"6*-35",player:"Mike Hamster"},
  {champion:"Nunu & Willump",r1:"Yeti Spotting Guide",r2:"Death's Foil",r3:"Lux's Incandescent Baton",star:"6*-45",player:"TwoStickmen"},
  {champion:"Nunu & Willump",r1:"Yeti Spotting Guide",r2:"Death's Foil",r3:"The Beast Within",star:"6*-46",player:"NarvalDream"},
  {champion:"Nunu & Willump",r1:"Searing Brilliance",r2:"The Beast Within",r3:"Stacked Deck",star:"5*-36",player:"Nazoric"},
  {champion:"Nunu & Willump",r1:"Searing Brilliance",r2:"Corrupted Star Fragment",r3:"Voidborne Carapace",star:"3*-34",player:"aoeuid"},
  {champion:"Nunu & Willump",r1:"Found Fortune",r2:"Spectral Scissors",r3:"Corrupted Star Fragment",star:"6*-35",player:"u/Zealousideal-Sky7829"},
  // ── Ornn ──
  {champion:"Ornn",r1:"Secret Technique",r2:"Loaded Dice",r3:"The Beast Within",star:"3*-50",player:"yramrax"},
  // ── Pyke ──
  {champion:"Pyke",r1:"Voidborne Carapace",r2:"Wicked Harvest",r3:"Stalker's Blade",star:"4*-37",player:"aoeuid"},
  {champion:"Pyke",r1:"Deadly Harpoon",r2:"Wicked Harvest",r3:"Stalker's Blade",star:"6*-42",player:"Nazoric"},
  {champion:"Pyke",r1:"Disciple of Shadows",r2:"Wicked Harvest",r3:"Succubus's Brand",star:"6*-40",player:"BumpyRoad"},
  {champion:"Pyke",r1:"Draconic Runes",r2:"Starfire Spellblade",r3:"Echoing Spirit",star:"6*-38",player:"u/TaskRabbit14"},
  {champion:"Pyke",r1:"The Beast Within",r2:"Searing Brilliance",r3:"Stalker's Blade",star:"6*-50",player:"Sydiem"},
  {champion:"Pyke",r1:"The Beast Within",r2:"Stacked Deck",r3:"Heart of Gold",star:"6*-50",player:"Hooded"},
  {champion:"Pyke",r1:"The Beast Within",r2:"Stacked Deck",r3:"Loaded Dice",star:"6*-38",player:"HPDARK"},
  {champion:"Pyke",r1:"The Beast Within",r2:"Stacked Deck",r3:"Lux's Incandescent Baton",star:"5*-36",player:"HPDARK"},
  {champion:"Pyke",r1:"The Beast Within",r2:"Stacked Deck",r3:"Black Shield",star:"6*-50",player:"cyclonus101"},
  // ── Samira ──
  {champion:"Samira",r1:"Packed Powder",r2:"Perfect Hex Core",r3:"Spellweaver's Symphony",star:"6*-47",player:"u/Chedder1998"},
  {champion:"Samira",r1:"Packed Powder",r2:"Spirit of the Buhru",r3:"Crownguard Inheritance",star:"6*-50",player:"Magnum Flare"},
  {champion:"Samira",r1:"Perfect Hex Core",r2:"Spirit of the Buhru",r3:"Crownguard Inheritance",star:"6*-34",player:"tomyang1117"},
  {champion:"Samira",r1:"Searing Brilliance",r2:"Champion's Purse",r3:"Perfect Hex Core",star:"5*-38",player:"Nazoric, ProfSE"},
  {champion:"Samira",r1:"Searing Brilliance",r2:"Chosen by the Stars",r3:"Hidden Tome",star:"4*-33",player:"aoeuid"},
  {champion:"Samira",r1:"Found Fortune",r2:"Loaded Dice",r3:"The Card Master's Gambit",star:"6*-34",player:"Hooded"},
  {champion:"Samira",r1:"Found Fortune",r2:"Echoing Spirit",r3:"Chosen by the Stars",star:"6*-50",player:"LehmonNation"},
  // ── Sett ──
  {champion:"Sett",r1:"Starforged Gauntlets",r2:"Luminous Orb",r3:"Chemtech Duplicator",star:"5*-35",player:"The Doomba, Hooded, Nazoric"},
  {champion:"Sett",r1:"The Beast Within",r2:"The Grand General's Counterplan",r3:"Chemtech Duplicator",star:"6*-35",player:"u/duelingdog"},
  {champion:"Sett",r1:"Archangel's Staff",r2:"The Grand General's Counterplan",r3:"Chemtech Duplicator",star:"6*-37",player:"tomyang1117"},
  {champion:"Sett",r1:"The Grand General's Counterplan",r2:"The Grand General's Counterplan",r3:"Chemtech Duplicator",star:"4*-50",player:"yramrax"},
  {champion:"Sett",r1:"Loaded Dice",r2:"Hidden Tome",r3:"Chemtech Duplicator",star:"6*-38",player:"jewl"},
  // ── Shyvana ──
  {champion:"Shyvana",r1:"Echoing Spirit",r2:"Voidborne Carapace",r3:"Guardian Angel",star:"4*-41",player:"aoeuid, LehmonNation"},
  {champion:"Shyvana",r1:"Echoing Spirit",r2:"Celestial Staff",r3:"Chosen by the Stars",star:"5*-39",player:"Sliverz"},
  {champion:"Shyvana",r1:"Echoing Spirit",r2:"Celestial Staff",r3:"The Beast Within",star:"6*-37",player:"Nazoric"},
  {champion:"Shyvana",r1:"Echoing Spirit",r2:"Celestial Staff",r3:"Guardian's Orb",star:"6*-43",player:"Blinddesire"},
  {champion:"Shyvana",r1:"Echoing Spirit",r2:"Celestial Staff",r3:"Voidborne Carapace",star:"6*-50",player:"Sydiem, ProfSE"},
  {champion:"Shyvana",r1:"Echoing Spirit",r2:"Loaded Dice",r3:"Voidborne Carapace",star:"4*-44",player:"HPDARK"},
  {champion:"Shyvana",r1:"Echoing Spirit",r2:"The Beast Within",r3:"Stalker's Blade",star:"6*-36",player:"u/Motigaismycity"},
  {champion:"Shyvana",r1:"Echoing Spirit",r2:"The Beast Within",r3:"Starfire Spellblade",star:"6*-39",player:"u/TaskRabbit14"},
  {champion:"Shyvana",r1:"Echoing Spirit",r2:"Draconic Runes",r3:"Starforged Gauntlets",star:"6*-37",player:"Hooded"},
  {champion:"Shyvana",r1:"Echoing Spirit",r2:"Chosen by the Stars",r3:"Loaded Dice",star:"6*-50",player:"cyclonus101, baseball7000"},
  {champion:"Shyvana",r1:"Full Build",r2:"Stalker's Blade",r3:"Voidborne Carapace",star:"5*-44",player:"u/Yorusluti"},
  {champion:"Shyvana",r1:"The Beast Within",r2:"Death's Foil",r3:"Black Shield",star:"6*-37",player:"Katisu"},
  {champion:"Shyvana",r1:"The Beast Within",r2:"Death's Foil",r3:"Stalker's Blade",star:"6*-44",player:"u/4002sacuL"},
  {champion:"Shyvana",r1:"Draconic Runes",r2:"Scales of Judgement",r3:"Stalker's Blade",star:"6*-50",player:"Mike Hamster"},
  // ── Soraka ──
  {champion:"Soraka",r1:"Starforged Gauntlets",r2:"Strength of Stone",r3:"Arcane Comet",star:"6*-31",player:"Chengsta"},
  {champion:"Soraka",r1:"Starforged Gauntlets",r2:"Strength of Stone",r3:"Celestial Staff",star:"6*-35",player:"TwoStickmen"},
  {champion:"Soraka",r1:"Strength of Stone",r2:"Cruel Experiments",r3:"The Grand General's Counterplan",star:"6*-36",player:"Hooded"},
  {champion:"Soraka",r1:"Celestial Staff",r2:"Cruel Experiments",r3:"Echoing Spirit",star:"6*-36",player:"Nazoric"},
  {champion:"Soraka",r1:"Celestial Staff",r2:"Cruel Experiments",r3:"Found Fortune",star:"6*-41",player:"Sydiem, Mike Hamster"},
  {champion:"Soraka",r1:"Celestial Staff",r2:"Chosen by the Stars",r3:"Hymn of Valor",star:"6*-50",player:"LehmonNation, ProfSE"},
  {champion:"Soraka",r1:"Celestial Staff",r2:"The Berserker's Buckle",r3:"Voidborne Carapace",star:"5*-35",player:"msh"},
  // ── Spirit Blossom Ahri ──
  {champion:"Spirit Blossom Ahri",r1:"Disciple of Shadows",r2:"Chosen by the Stars",r3:"Lux's Incandescent Baton",star:"4*-47",player:"HPDARK, diaversai"},
  {champion:"Spirit Blossom Ahri",r1:"Searing Brilliance",r2:"Echoing Spirit",r3:"The Beast Within",star:"6*-50",player:"Nazoric, aoeuid"},
  {champion:"Spirit Blossom Ahri",r1:"Found Fortune",r2:"Packed Powder",r3:"Essence Theft",star:"6*-50",player:"u/Cindrojn"},
  {champion:"Spirit Blossom Ahri",r1:"Strength of Stone",r2:"Loaded Dice",r3:"Defense Spending",star:"4*-39",player:"BumpyRoad"},
  {champion:"Spirit Blossom Ahri",r1:"Strength of Stone",r2:"Spectral Scissors",r3:"Corrupted Star Fragment",star:"7*-50",player:"u/Cyphren"},
  {champion:"Spirit Blossom Ahri",r1:"Strength of Stone",r2:"Attendant Spirits",r3:"Corrupted Star Fragment",star:"7*-50",player:"u/TaskRabbit14"},
  // ── Spirit Blossom Evelynn ──
  {champion:"Spirit Blossom Evelynn",r1:"Lux's Incandescent Baton",r2:"Loaded Dice",r3:"The Beast Within",star:"4*-38",player:"HPDARK"},
  {champion:"Spirit Blossom Evelynn",r1:"Chosen by the Stars",r2:"Disciple of Shadows",r3:"Found Fortune",star:"4*-43",player:"diaversai"},
  {champion:"Spirit Blossom Evelynn",r1:"Chosen by the Stars",r2:"Disciple of Shadows",r3:"Lux's Incandescent Baton",star:"4*-50",player:"ProfSE, Hooded"},
  {champion:"Spirit Blossom Evelynn",r1:"Strength of Stone",r2:"Frozen Tomb",r3:"Luminous Orb",star:"6*-50",player:"u/ToaOfTheVoid"},
  {champion:"Spirit Blossom Evelynn",r1:"Siphoned Sorrow",r2:"Strength of Stone",r3:"The Beast Within",star:"5*-50",player:"Nazoric"},
  {champion:"Spirit Blossom Evelynn",r1:"Siphoned Sorrow",r2:"Strength of Stone",r3:"Hidden Tome",star:"7*-50",player:"u/Akazaka_"},
  // ── Spirit Blossom Kindred ──
  {champion:"Spirit Blossom Kindred",r1:"Frozen Tomb",r2:"Chemtech Duplicator",r3:"Troll King's Crown",star:"4*-48",player:"lolguy999, Mike Hamster"},
  {champion:"Spirit Blossom Kindred",r1:"The Beast Within",r2:"The Berserker's Buckle",r3:"Voidborne Carapace",star:"5*-50",player:"aoeuid"},
  {champion:"Spirit Blossom Kindred",r1:"The Beast Within",r2:"Disciple of Shadows",r3:"Wicked Harvest",star:"5*-39",player:"BumpyRoad"},
  {champion:"Spirit Blossom Kindred",r1:"Troll King's Crown",r2:"The Grand General's Counterplan",r3:"Archangel's Staff",star:"7*-49",player:"darwin"},
  {champion:"Spirit Blossom Kindred",r1:"Echoing Spirit",r2:"The Grand General's Counterplan",r3:"Wicked Harvest",star:"5*-50",player:"Huffy"},
  {champion:"Spirit Blossom Kindred",r1:"Echoing Spirit",r2:"The Grand General's Counterplan",r3:"Voidborne Carapace",star:"6*-44",player:"Nuimee"},
  {champion:"Spirit Blossom Kindred",r1:"Echoing Spirit",r2:"The Grand General's Counterplan",r3:"The Grand General's Counterplan",star:"6*-50",player:"u/TaskRabbit14"},
  {champion:"Spirit Blossom Kindred",r1:"Echoing Spirit",r2:"The Beast Within",r3:"Loaded Dice",star:"6*-50",player:"HPDARK"},
  {champion:"Spirit Blossom Kindred",r1:"Echoing Spirit",r2:"The Beast Within",r3:"Living Weapon",star:"7*-50",player:"Chengsta"},
  {champion:"Spirit Blossom Kindred",r1:"Echoing Spirit",r2:"The Beast Within",r3:"The Grand General's Counterplan",star:"7*",player:"ProfSE, Hooded, SSJ5GOKU"},
  {champion:"Spirit Blossom Kindred",r1:"Echoing Spirit",r2:"Champion's Purse",r3:"The Grand General's Counterplan",star:"7*-50",player:"NarvalDream"},
  {champion:"Spirit Blossom Kindred",r1:"Swain's Raven Army",r2:"Packed Powder",r3:"The Grand General's Counterplan",star:"6*-50",player:"Nazoric"},
  // ── Spirit Blossom Master Yi ──
  {champion:"Spirit Blossom Master Yi",r1:"Secret Technique",r2:"The Beast Within",r3:"Lux's Incandescent Baton",star:"5*-50",player:"LehmonNation, HPDARK, Hooded"},
  {champion:"Spirit Blossom Master Yi",r1:"Secret Technique",r2:"The Beast Within",r3:"The Scourge's Stash",star:"6*-44",player:"Catamarano"},
  {champion:"Spirit Blossom Master Yi",r1:"Secret Technique",r2:"The Beast Within",r3:"Searing Brilliance",star:"6*-48",player:"Nazoric, Magnum Flare, Chengsta"},
  {champion:"Spirit Blossom Master Yi",r1:"Secret Technique",r2:"The Beast Within",r3:"Loaded Dice",star:"5*-44",player:"BumpyRoad"},
  {champion:"Spirit Blossom Master Yi",r1:"Perfect Hex Core",r2:"The Beast Within",r3:"Black Shield",star:"6*-50",player:"Sebs"},
  {champion:"Spirit Blossom Master Yi",r1:"Perfect Hex Core",r2:"Timehonored Blade",r3:"Secret Technique",star:"6*-50",player:"u/Airtnp"},
  {champion:"Spirit Blossom Master Yi",r1:"Perfect Hex Core",r2:"Timehonored Blade",r3:"Loaded Dice",star:"6*-36",player:"Mike Hamster"},
  // ── Spirit Blossom Teemo ──
  {champion:"Spirit Blossom Teemo",r1:"Mischiefmaker's Flute",r2:"Harmless Scarecrow",r3:"Frozen Tomb",star:"4*-50",player:"Nazoric"},
  {champion:"Spirit Blossom Teemo",r1:"Mischiefmaker's Flute",r2:"Harmless Scarecrow",r3:"Hextech Rifle",star:"7*-50",player:"u/kradsavage"},
  {champion:"Spirit Blossom Teemo",r1:"Mischiefmaker's Flute",r2:"Harmless Scarecrow",r3:"Echoing Spirit",star:"6*-48",player:"RoloRolla"},
  {champion:"Spirit Blossom Teemo",r1:"Mischiefmaker's Flute",r2:"Harmless Scarecrow",r3:"The Bounty Hunter's Renown",star:"7*-50",player:"Tangolino"},
  {champion:"Spirit Blossom Teemo",r1:"Mischiefmaker's Flute",r2:"Harmless Scarecrow",r3:"Wicked Harvest",star:"7*-50",player:"u/dt_again, TwoStickmen"},
  {champion:"Spirit Blossom Teemo",r1:"Mischiefmaker's Flute",r2:"Wicked Harvest",r3:"Disciple of Shadows",star:"4*-50",player:"yramrax"},
  {champion:"Spirit Blossom Teemo",r1:"Harmless Scarecrow",r2:"Chemtech Duplicator",r3:"The Grand General's Counterplan",star:"7*-50",player:"jewl"},
  {champion:"Spirit Blossom Teemo",r1:"Disciple of Shadows",r2:"Loaded Dice",r3:"Hidden Tome",star:"5*-45",player:"BumpyRoad"},
  {champion:"Spirit Blossom Teemo",r1:"Swain's Raven Army",r2:"Packed Powder",r3:"Hextech Rifle",star:"5*-38",player:"Frumby DaGoblin, Catamarano"},
  {champion:"Spirit Blossom Teemo",r1:"Echoing Spirit",r2:"Condenser",r3:"Found Fortune",star:"4*-34",player:"VodopadUmraza"},
  // ── Spirit Blossom Yasuo ──
  {champion:"Spirit Blossom Yasuo",r1:"Perfect Hex Core",r2:"Yasuo's Windblade",r3:"The Grand General's Counterplan",star:"3*-36",player:"VodopadUmraza"},
  {champion:"Spirit Blossom Yasuo",r1:"Perfect Hex Core",r2:"Yasuo's Windblade",r3:"Deck of Destiny",star:"5*-50",player:"LehmonNation, Nazoric, u/Met2003"},
  {champion:"Spirit Blossom Yasuo",r1:"Perfect Hex Core",r2:"Yasuo's Windblade",r3:"Searing Brilliance",star:"4*-50",player:"ProfSE"},
  {champion:"Spirit Blossom Yasuo",r1:"Perfect Hex Core",r2:"Found Fortune",r3:"Searing Brilliance",star:"4*-50",player:"eoeuid"},
  {champion:"Spirit Blossom Yasuo",r1:"Perfect Hex Core",r2:"Black Shield",r3:"Portal Pals",star:"6*-47",player:"u/Katisurinkai"},
  {champion:"Spirit Blossom Yasuo",r1:"Perfect Hex Core",r2:"Spellweaver's Symphony",r3:"Portal Pals",star:"4*-50",player:"Sirikuku, diaversai"},
  {champion:"Spirit Blossom Yasuo",r1:"The Beast Within",r2:"Loaded Dice",r3:"Lux's Incandescent Baton",star:"4*-47",player:"HPDARK"},
  {champion:"Spirit Blossom Yasuo",r1:"Hidden Tome",r2:"Scales of Judgement",r3:"Oath of the Guardians",star:"5*-46",player:"BumpyRoad"},
  // ── Swain ──
  {champion:"Swain",r1:"Swain's Raven Army",r2:"The Curator's Gatebreaker",r3:"Found Fortune",star:"6*-36",player:"u/weipenghuang"},
  {champion:"Swain",r1:"Swain's Raven Army",r2:"Shock & Awe",r3:"Searing Brilliance",star:"6*-36",player:"Nazoric"},
  {champion:"Swain",r1:"Swain's Raven Army",r2:"Shock & Awe",r3:"Big Guns",star:"6*-50",player:"cyclonus101"},
  {champion:"Swain",r1:"Swain's Raven Army",r2:"Deck of Destiny",r3:"Big Guns",star:"6*-39",player:"Mike Hamster"},
  {champion:"Swain",r1:"Swain's Raven Army",r2:"Packed Powder",r3:"Big Guns",star:"6*-50",player:"LehmonNation, diaversai, baseball7000"},
  {champion:"Swain",r1:"Swain's Raven Army",r2:"Packed Powder",r3:"Found Fortune",star:"6*-40",player:"u/legner_01, Bushi, ProfSE"},
  {champion:"Swain",r1:"Swain's Raven Army",r2:"Packed Powder",r3:"Loaded Dice",star:"6*-45",player:"u/Katisurinkai"},
  {champion:"Swain",r1:"Swain's Raven Army",r2:"Packed Powder",r3:"Searing Brilliance",star:"6*-50",player:"Chengsta"},
  {champion:"Swain",r1:"Swain's Raven Army",r2:"Packed Powder",r3:"Riptide Battery",star:"6*-45",player:"ItzYana, u/Airtnp, yuemoonn"},
  {champion:"Swain",r1:"Swain's Raven Army",r2:"Packed Powder",r3:"Dreadway Chase Gun",star:"6*-50",player:"u/Cyphren"},
  {champion:"Swain",r1:"Swain's Raven Army",r2:"Packed Powder",r3:"Chemtech Duplicator",star:"6*-50",player:"Nuimee"},
  {champion:"Swain",r1:"Packed Powder",r2:"Guardian Angel",r3:"Voidborne Carapace",star:"6*-38",player:"aoeuid"},
  {champion:"Swain",r1:"Loaded Dice",r2:"Packed Powder",r3:"Searing Brilliance",star:"6*-43",player:"Alkaloid"},
  {champion:"Swain",r1:"Loaded Dice",r2:"Big Guns",r3:"Frozen Tomb",star:"6*-44",player:"HPDARK"},
  // ── Taliyah ──
  {champion:"Taliyah",r1:"Whisper",r2:"Crownguard Inheritance",r3:"Tempest Blade",star:"6*-50",player:"LehmonNation"},
  {champion:"Taliyah",r1:"Icon of Valhir",r2:"Found Fortune",r3:"Laurent Bladerack",star:"6*-37",player:"Nazoric"},
  {champion:"Taliyah",r1:"Starforged Gauntlets",r2:"Luminous Orb",r3:"Laurent Bladerack",star:"6*-36",player:"Hooded"},
  {champion:"Taliyah",r1:"Frozen Tomb",r2:"Packed Powder",r3:"Swain's Raven Army",star:"6*-40",player:"Chengsta"},
  {champion:"Taliyah",r1:"Frozen Tomb",r2:"Starforged Gauntlets",r3:"Luminous Orb",star:"6*-37",player:"The Moral Support"},
  // ── Teemo ──
  {champion:"Teemo",r1:"Echoing Spirit",r2:"Guardian's Orb",r3:"Guardian's Orb",star:"3*-49",player:"Suurkyy"},
  // ── The Poro King ──
  {champion:"The Poro King",r1:"The Beast Within",r2:"Searing Brilliance",r3:"Chemtech Duplicator",star:"5*-40",player:"aoeuid"},
  {champion:"The Poro King",r1:"Disciple of Shadows",r2:"Black Shield",r3:"Chemtech Duplicator",star:"6*-38",player:"lolguy999, RoloRolla"},
  {champion:"The Poro King",r1:"Spirit of the Buhru",r2:"Black Shield",r3:"Chemtech Duplicator",star:"6*-46",player:"SSJ5GOKU, Katisu"},
  {champion:"The Poro King",r1:"Spirit of the Buhru",r2:"Black Shield",r3:"Secret Technique",star:"6*-38",player:"Nazoric"},
  {champion:"The Poro King",r1:"Spirit of the Buhru",r2:"Black Shield",r3:"Searing Brilliance",star:"6*-34",player:"Hooded"},
  {champion:"The Poro King",r1:"Spirit of the Buhru",r2:"Royal Nibbles",r3:"The Beast Within",star:"6*-37",player:"u/TaskRabbit14"},
  {champion:"The Poro King",r1:"Spirit of the Buhru",r2:"Royal Nibbles",r3:"Chemtech Duplicator",star:"4*-47",player:"Zarkkast"},
  // ── Thresh ──
  {champion:"Thresh",r1:"Found Fortune",r2:"Guardian's Orb",r3:"Essence Theft",star:"3*-38",player:"VodopadUmraza"},
  {champion:"Thresh",r1:"Found Fortune",r2:"Corrupted Star Fragment",r3:"Wicked Harvest",star:"6*-37",player:"u/DoubleSummon"},
  {champion:"Thresh",r1:"Echoing Spirit",r2:"Found Fortune",r3:"Guardian's Orb",star:"4*-42",player:"Alex"},
  {champion:"Thresh",r1:"Oath of the Guardians",r2:"Echoing Spirit",r3:"Star Gem",star:"6*-50",player:"ProfSE"},
  {champion:"Thresh",r1:"Oath of the Guardians",r2:"Siren's Call",r3:"Star Gem",star:"6*-38",player:"Nazoric"},
  {champion:"Thresh",r1:"Oath of the Guardians",r2:"Star Gem",r3:"Wicked Harvest",star:"6*-35",player:"The Moral Support"},
  {champion:"Thresh",r1:"Soul Lantern",r2:"Star Gem",r3:"Spirit Forge",star:"6*-46",player:"Hooded"},
  {champion:"Thresh",r1:"Soul Lantern",r2:"Cease and Desist",r3:"Fear-Cleaving Axe",star:"6*-50",player:"LehmonNation, TwoStickmen"},
  // ── Tryndamere ──
  {champion:"Tryndamere",r1:"Starforged Gauntlets",r2:"The Beast Within",r3:"Siren's Call",star:"6*-38",player:"Nazoric"},
  {champion:"Tryndamere",r1:"Starforged Gauntlets",r2:"Echoing Spirit",r3:"Portal Pals",star:"6*-46",player:"powercuties"},
  {champion:"Tryndamere",r1:"Starforged Gauntlets",r2:"Echoing Spirit",r3:"Voidborne Carapace",star:"5*-42",player:"aoeuid"},
  {champion:"Tryndamere",r1:"Starforged Gauntlets",r2:"Echoing Spirit",r3:"Chemtech Duplicator",star:"6*-38",player:"lolguy999, HPDARK, Hooded"},
  {champion:"Tryndamere",r1:"Echoing Spirit",r2:"Portal Pals",r3:"Chemtech Duplicator",star:"6*-34",player:"The Moral Support"},
  // ── Twisted Fate ──
  {champion:"Twisted Fate",r1:"Perfect Hex Core",r2:"Spellweaver's Symphony",r3:"Big Guns",star:"3*-34",player:"VodopadUmraza"},
  {champion:"Twisted Fate",r1:"Deck of Destiny",r2:"Swain's Raven Army",r3:"Packed Powder",star:"6*-49",player:"Chengsta"},
  {champion:"Twisted Fate",r1:"Echoing Spirit",r2:"Swain's Raven Army",r3:"Packed Powder",star:"5*-34",player:"Jaize"},
  {champion:"Twisted Fate",r1:"Echoing Spirit",r2:"Found Fortune",r3:"Stacked Deck",star:"5*-50",player:"cyclonus101"},
  {champion:"Twisted Fate",r1:"Echoing Spirit",r2:"Deck of Destiny",r3:"Stacked Deck",star:"6*-44",player:"RoloRolla"},
  {champion:"Twisted Fate",r1:"Echoing Spirit",r2:"Deck of Destiny",r3:"Searing Brilliance",star:"6*-50",player:"Sydiem, ProfSE"},
  {champion:"Twisted Fate",r1:"Echoing Spirit",r2:"Deck of Destiny",r3:"Big Guns",star:"6*-50",player:"jewl"},
  {champion:"Twisted Fate",r1:"Echoing Spirit",r2:"Loaded Dice",r3:"The Card Master's Gambit",star:"6*-37",player:"HPDARK"},
  {champion:"Twisted Fate",r1:"Big Guns",r2:"Chosen by the Stars",r3:"Searing Brilliance",star:"6*-38",player:"Nazoric"},
  {champion:"Twisted Fate",r1:"Big Guns",r2:"Luden's Tempest",r3:"Chemtech Duplicator",star:"6*-35",player:"The Moral Support"},
  {champion:"Twisted Fate",r1:"Searing Brilliance",r2:"Deck of Destiny",r3:"Chemtech Duplicator",star:"5*-42",player:"Mike Hamster"},
  // ── Udyr ──
  {champion:"Udyr",r1:"Swain's Raven Army",r2:"Packed Powder",r3:"Secret Technique",star:"6*-37",player:"u/Ar341"},
  {champion:"Udyr",r1:"Disciple of Shadows",r2:"Hidden Tome",r3:"Secret Technique",star:"6*-35",player:"TwoStickmen"},
  {champion:"Udyr",r1:"Innervating Locket",r2:"Hidden Tome",r3:"Chemtech Duplicator",star:"6*-37",player:"u/freehugs33"},
  {champion:"Udyr",r1:"Black Shield",r2:"Sentinel's Plate",r3:"Voidborne Carapace",star:"6*-50",player:"u/Smritilor"},
  // ── Vayne ──
  {champion:"Vayne",r1:"Death's Foil",r2:"The Beast Within",r3:"Lost Chapter",star:"6*-37",player:"yuemoonn"},
  {champion:"Vayne",r1:"Death's Foil",r2:"The Beast Within",r3:"Hidden Tome",star:"6*-41",player:"RoloRolla"},
  {champion:"Vayne",r1:"Death's Foil",r2:"The Beast Within",r3:"Deadly Harpoon",star:"6*-35",player:"Nazoric"},
  {champion:"Vayne",r1:"Death's Foil",r2:"Hidden Tome",r3:"Chosen by the Stars",star:"6*-50",player:"LehmonNation, aoeuid, baseball7000"},
  {champion:"Vayne",r1:"Death's Foil",r2:"Lost Chapter",r3:"Chosen by the Stars",star:"6*-40",player:"tomyang1117"},
  {champion:"Vayne",r1:"Chosen by the Stars",r2:"Hidden Tome",r3:"Voidborne Carapace",star:"6*-44",player:"jewl"},
  {champion:"Vayne",r1:"Living Weapon",r2:"Hidden Tome",r3:"Voidborne Carapace",star:"6*-40",player:"u/freehugs33"},
  // ── Vex ──
  {champion:"Vex",r1:"Deck of Destiny",r2:"Searing Brilliance",r3:"Big Guns",star:"6*-44",player:"Nazoric, baseball7000"},
  {champion:"Vex",r1:"Big Guns",r2:"Searing Brilliance",r3:"Chemtech Duplicator",star:"4*-44",player:"aoeuid"},
  {champion:"Vex",r1:"Big Guns",r2:"Frozen Tomb",r3:"Loaded Dice",star:"6*-39",player:"HPDARK, Hooded"},
  {champion:"Vex",r1:"Frozen Tomb",r2:"Echoing Spirit",r3:"Black Shield",star:"6*-42",player:"Erian"},
  {champion:"Vex",r1:"Fear-Cleaving Axe",r2:"Death's Foil",r3:"Utmost Despair",star:"6*-37",player:"yuemoonn"},
  {champion:"Vex",r1:"Fear-Cleaving Axe",r2:"Hidden Tome",r3:"Death's Foil",star:"6*-40",player:"u/SilverScribe15"},
  {champion:"Vex",r1:"Fear-Cleaving Axe",r2:"Big Guns",r3:"Utmost Despair",star:"6*-40",player:"2ndTony"},
  {champion:"Vex",r1:"Fear-Cleaving Axe",r2:"Big Guns",r3:"Black Shield",star:"6*-50",player:"Magnum Flare"},
  {champion:"Vex",r1:"Fear-Cleaving Axe",r2:"Utmost Despair",r3:"Utmost Despair",star:"6*-50",player:"Chengsta"},
  {champion:"Vex",r1:"Fear-Cleaving Axe",r2:"Echoing Spirit",r3:"Queen's Embrace",star:"6*-36",player:"u/TaskRabbit14"},
  {champion:"Vex",r1:"Fear-Cleaving Axe",r2:"Guardian Angel",r3:"Voidborne Carapace",star:"4*-50",player:"cyclonus101"},
  {champion:"Vex",r1:"Guardian Angel",r2:"Voidborne Carapace",r3:"Utmost Despair",star:"6*-38",player:"CrabbyCharix"},
  {champion:"Vex",r1:"Guardian Angel",r2:"Voidborne Carapace",r3:"Wicked Harvest",star:"6*-50",player:"LehmonNation, u/Yorusluti, u/Met2003"},
  // ── Vi ──
  {champion:"Vi",r1:"Strength of Stone",r2:"Searing Brilliance",r3:"Starforged Gauntlets",star:"3*-34",player:"aoeuid"},
  {champion:"Vi",r1:"Deck of Destiny",r2:"Searing Brilliance",r3:"The Beast Within",star:"5*-34",player:"Nazoric"},
  {champion:"Vi",r1:"Cease and Desist",r2:"Searing Brilliance",r3:"Disciple of Shadows",star:"6*-50",player:"ProfSE"},
  {champion:"Vi",r1:"Cease and Desist",r2:"Death's Foil",r3:"The Curator's Gatebreaker",star:"6*-47",player:"NarvalDream"},
  {champion:"Vi",r1:"Cease and Desist",r2:"The Curator's Gatebreaker",r3:"The Curator's Gatebreaker",star:"6*-50",player:"LehmonNation"},
  // ── Viego ──
  {champion:"Viego",r1:"Voidborne Carapace",r2:"Wicked Harvest",r3:"Corrupted Star Fragment",star:"5*-35",player:"CrabbyCharix"},
  {champion:"Viego",r1:"Starforged Gauntlets",r2:"Spectral Scissors",r3:"Disciple of Shadows",star:"6*-41",player:"HPDARK, Erian, Chengsta"},
  {champion:"Viego",r1:"Starforged Gauntlets",r2:"Spectral Scissors",r3:"Searing Brilliance",star:"6*-50",player:"LehmonNation"},
  {champion:"Viego",r1:"Starforged Gauntlets",r2:"Spectral Scissors",r3:"Cease and Desist",star:"6*-50",player:"cyclonus101"},
  {champion:"Viego",r1:"Starforged Gauntlets",r2:"Spectral Scissors",r3:"Black Shield",star:"6*-50",player:"Magnum Flare"},
  {champion:"Viego",r1:"Starforged Gauntlets",r2:"Spectral Scissors",r3:"Corrupted Star Fragment",star:"6*-40",player:"u/Katisurinkai"},
  {champion:"Viego",r1:"Disciple of Shadows",r2:"Spectral Scissors",r3:"Corrupted Star Fragment",star:"6*-39",player:"u/Simonirico"},
  {champion:"Viego",r1:"Chosen by the Stars",r2:"Spectral Scissors",r3:"Corrupted Star Fragment",star:"6*-44",player:"u/TB-124"},
  {champion:"Viego",r1:"The Beast Within",r2:"Spectral Scissors",r3:"Corrupted Star Fragment",star:"6*-47",player:"xopuxir"},
  {champion:"Viego",r1:"Spectral Scissors",r2:"Corrupted Star Fragment",r3:"Stalker's Blade",star:"6*-41",player:"u/DurianInPizza"},
  {champion:"Viego",r1:"Spectral Scissors",r2:"Scales of Judgement",r3:"Disciple of Shadows",star:"6*-50",player:"u/Airtnp"},
  {champion:"Viego",r1:"Disciple of Shadows",r2:"Found Fortune",r3:"Corrupted Star Fragment",star:"6*-50",player:"Xatik"},
  {champion:"Viego",r1:"Black Shield",r2:"Stacked Deck",r3:"Portal Pals",star:"6*-45",player:"Nazoric"},
  {champion:"Viego",r1:"Guardian Angel",r2:"Corrupted Star Fragment",r3:"Stalker's Blade",star:"6*-35",player:"Yatotoro"},
  // ── Viktor ──
  {champion:"Viktor",r1:"Echoing Spirit",r2:"Perfect Hex Core",r3:"Hymn of Valor",star:"6*-39",player:"Catamarano, Magnum Flare"},
  {champion:"Viktor",r1:"Echoing Spirit",r2:"Perfect Hex Core",r3:"Chemtech Duplicator",star:"6*-50",player:"Nuimee"},
  {champion:"Viktor",r1:"Echoing Spirit",r2:"Perfect Hex Core",r3:"Oath of the Guardians",star:"6*-44",player:"Nazoric"},
  {champion:"Viktor",r1:"Echoing Spirit",r2:"Hidden Tome",r3:"Hymn of Valor",star:"6*-40",player:"HPDARK"},
  {champion:"Viktor",r1:"Echoing Spirit",r2:"Chosen by the Stars",r3:"Hymn of Valor",star:"6*-50",player:"ProfSE"},
  {champion:"Viktor",r1:"Echoing Spirit",r2:"The Beast Within",r3:"Condenser",star:"6*-38",player:"The Moral Support"},
  {champion:"Viktor",r1:"Echoing Spirit",r2:"Guardian Angel",r3:"Voidborne Carapace",star:"6*-50",player:"LehmonNation"},
  {champion:"Viktor",r1:"Echoing Spirit",r2:"Hymn of Valor",r3:"Spirit Forge",star:"6*-50",player:"Hooded"},
  {champion:"Viktor",r1:"Perfect Hex Core",r2:"Found Fortune",r3:"Chemtech Duplicator",star:"3*-34",player:"VodopadUmraza"},
  {champion:"Viktor",r1:"Perfect Hex Core",r2:"Hidden Tome",r3:"Hymn of Valor",star:"6*-50",player:"u/Airtnp, Mike Hamster"},
  // ── Volibear ──
  {champion:"Volibear",r1:"Starforged Gauntlets",r2:"Portal Pals",r3:"Big Guns",star:"6*-41",player:"HPDARK"},
  {champion:"Volibear",r1:"Starforged Gauntlets",r2:"Portal Pals",r3:"Icon of Valhir",star:"6*-50",player:"NarvalDream"},
  {champion:"Volibear",r1:"Starforged Gauntlets",r2:"Portal Pals",r3:"Stacked Deck",star:"6*-37",player:"Hooded, ProfSE"},
  {champion:"Volibear",r1:"Starforged Gauntlets",r2:"Portal Pals",r3:"Loaded Dice",star:"6*-41",player:"HPDARK"},
  {champion:"Volibear",r1:"Starforged Gauntlets",r2:"Cease and Desist",r3:"Stacked Deck",star:"5*-39",player:"Nazoric"},
  {champion:"Volibear",r1:"Starforged Gauntlets",r2:"Cease and Desist",r3:"The Beast Within",star:"6*-50",player:"cyclonus101, baseball7000"},
  {champion:"Volibear",r1:"Starforged Gauntlets",r2:"Cease and Desist",r3:"Great Talons",star:"6*-50",player:"Sydiem"},
  // ── Warwick ──
  {champion:"Warwick",r1:"Cruel Experiments",r2:"Loaded Dice",r3:"Ravenous Hydra",star:"4*-38",player:"BumpyRoad"},
  {champion:"Warwick",r1:"Black Shield",r2:"Voidborne Carapace",r3:"Wicked Harvest",star:"6*-36",player:"Katisu"},
  {champion:"Warwick",r1:"Wicked Harvest",r2:"Succubus's Brand",r3:"Voidborne Carapace",star:"5*-35",player:"Catamarano, baseball7000, RoloRolla"},
  {champion:"Warwick",r1:"Deadly Harpoon",r2:"Disciple of Shadows",r3:"Succubus's Brand",star:"6*-37",player:"Huffy"},
  {champion:"Warwick",r1:"Cruel Experiments",r2:"Celestial Staff",r3:"Death's Foil",star:"6*-39",player:"Nazoric"},
  {champion:"Warwick",r1:"Voidborne Carapace",r2:"Loaded Dice",r3:"Celestial Staff",star:"6*-50",player:"CheetosOwned"},
  // ── Yasuo ──
  {champion:"Yasuo",r1:"Tempest Blade",r2:"Voidborne Carapace",r3:"Everfrost",star:"3*-43",player:"diaversai, CrabbyCharix, TyeS"},
  {champion:"Yasuo",r1:"Tempest Blade",r2:"The Grand General's Counterplan",r3:"Everfrost",star:"6*-31",player:"Xatik"},
  {champion:"Yasuo",r1:"Tempest Blade",r2:"Full Build",r3:"Loaded Dice",star:"6*-40",player:"u/rybicky"},
  {champion:"Yasuo",r1:"Echoing Spirit",r2:"Tempest Blade",r3:"Voidborne Carapace",star:"6*-42",player:"Nuimee"},
  {champion:"Yasuo",r1:"Echoing Spirit",r2:"Mischiefmaker's Flute",r3:"The Grand General's Counterplan",star:"5*-34",player:"Sliverz"},
  {champion:"Yasuo",r1:"Echoing Spirit",r2:"Mischiefmaker's Flute",r3:"Draconic Runes",star:"6*-36",player:"u/TaskRabbit14"},
  {champion:"Yasuo",r1:"Echoing Spirit",r2:"Black Shield",r3:"Tempest Blade",star:"6*-38",player:"u/DoubleSummon"},
  {champion:"Yasuo",r1:"Echoing Spirit",r2:"Chosen by the Stars",r3:"Everfrost",star:"5*-33",player:"RoloRolla"},
  {champion:"Yasuo",r1:"Yasuo's Windblade",r2:"Echoing Spirit",r3:"Tempest Blade",star:"6*-50",player:"u/legner_01"},
  {champion:"Yasuo",r1:"Yasuo's Windblade",r2:"Echoing Spirit",r3:"The Hand of Noxus",star:"6*-35",player:"Nazoric"},
  {champion:"Yasuo",r1:"Yasuo's Windblade",r2:"The Beast Within",r3:"Stacked Deck",star:"6*-50",player:"u/kinkasho"},
  {champion:"Yasuo",r1:"Yasuo's Windblade",r2:"Searing Brilliance",r3:"Tempest Blade",star:"6*-35",player:"Chengsta"},
  {champion:"Yasuo",r1:"Yasuo's Windblade",r2:"Stacked Deck",r3:"Voidborne Carapace",star:"6*-50",player:"ProfSE"},
  {champion:"Yasuo",r1:"Yasuo's Windblade",r2:"Tempest Blade",r3:"Everfrost",star:"6*-36",player:"Yuemoonn"},
  {champion:"Yasuo",r1:"Yasuo's Windblade",r2:"Tempest Blade",r3:"Voidborne Carapace",star:"6*-50",player:"LehmonNation"},
  // ── Yuumi ──
  {champion:"Yuumi",r1:"Perfect Hex Core",r2:"Spirit of the Buhru",r3:"Galeforce",star:"6*-36",player:"Nazoric"},
  {champion:"Yuumi",r1:"Perfect Hex Core",r2:"Full Build",r3:"Galeforce",star:"5*-35",player:"Mike Hamster, aoeuid, cyclonus101"},
  {champion:"Yuumi",r1:"Perfect Hex Core",r2:"Black Shield",r3:"Loaded Dice",star:"6*-38",player:"Katisu"},
  {champion:"Yuumi",r1:"The Beast Within",r2:"Black Shield",r3:"Full Build",star:"6*-36",player:"The Moral Support"},
];
